"""initial_schema

Revision ID: 350d9942b399
Revises: 
Create Date: 2026-03-07 02:40:33.115829

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '350d9942b399'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('founded_year', sa.SmallInteger(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('founded_year BETWEEN 1800 AND 2100', name='chk_brand_founded_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='One row per car manufacturer, e.g. Toyota, BMW.'
    )
    op.create_index('idx_brands_active', 'car_brands', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_brands_name', 'car_brands', ['name'], unique=False)
    op.create_table('complaint_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.Enum('AUTOMOTIVE', 'INSURANCE', 'GENERAL', name='entity_domain', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='Seed table - pre-populated at deployment; referenced by NLP results.'
    )
    op.create_index('idx_complaint_domain', 'complaint_types', ['domain'], unique=False)
    op.create_table('insurance_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('founded_year BETWEEN 1800 AND 2100', name='chk_insurer_founded'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='One row per insurance company, e.g. AXA, Allianz.'
    )
    op.create_index('idx_insurers_active', 'insurance_companies', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_insurers_country', 'insurance_companies', ['country'], unique=False)
    op.create_index('idx_insurers_name', 'insurance_companies', ['name'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False, comment='Normalized keyword term (lowercase, stripped).'),
    sa.Column('domain', sa.Enum('AUTOMOTIVE', 'INSURANCE', 'GENERAL', name='entity_domain', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term'),
    comment='Keyword vocabulary - terms extracted from reviews and articles by NLP pipeline.'
    )
    op.create_index('idx_keywords_domain', 'keywords', ['domain'], unique=False)
    op.create_table('kpi_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False, comment="e.g. 'avg_rating', 'brand_sentiment_score', 'market_share'."),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment="Domain entity referencing this KPI, e.g. 'car_model', 'insurance_company'."),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('granularity', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='kpi_granularity', create_constraint=True), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional extra context: filters, model version, formula used.'),
    sa.CheckConstraint('char_length(entity_type) > 0', name='chk_kpi_entity_nonempty'),
    sa.CheckConstraint('char_length(kpi_name) > 0', name='chk_kpi_name_nonempty'),
    sa.PrimaryKeyConstraint('id', 'computed_at'),
    comment='Append-only KPI warehouse - partitioned yearly; never UPDATE rows.',
    postgresql_partition_by='RANGE (computed_at)'
    )
    op.create_index('idx_kpi_entity', 'kpi_metrics', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_kpi_granularity', 'kpi_metrics', ['granularity'], unique=False)
    op.create_index('idx_kpi_name_computed', 'kpi_metrics', ['kpi_name', 'computed_at'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='pipeline_status', create_constraint=True), nullable=False),
    sa.Column('records_scraped', sa.Integer(), nullable=False),
    sa.Column('records_stored', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Orchestration-level audit trail; complements fine-grained scraping_runs.'
    )
    op.create_index('idx_pipeline_start', 'pipeline_runs', ['started_at'], unique=False)
    op.create_index('idx_pipeline_status', 'pipeline_runs', ['status'], unique=False)
    op.create_index('idx_pipeline_task', 'pipeline_runs', ['task_name'], unique=False)
    op.create_index('idx_pipeline_task_start', 'pipeline_runs', ['task_name', 'started_at'], unique=False)
    op.create_table('review_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('AUTOMOTIVE_REVIEW', 'NEWS_BLOG', 'MARKETPLACE', 'INSURANCE_REVIEW', 'FORUM', 'PRICING_PAGE', 'TREND_ARTICLE', name='source_type', create_constraint=True), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=4, scale=3), nullable=False, comment='0-1 score representing source data quality / trustworthiness.'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reliability_score BETWEEN 0 AND 1', name='chk_reliability_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Central source registry; all scraped rows carry a source_id FK to here.'
    )
    op.create_index('idx_sources_active', 'review_sources', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_sources_type', 'review_sources', ['source_type'], unique=False)
    op.create_table('scraping_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Surrogate UUID primary key.'),
    sa.Column('task_name', sa.String(length=100), nullable=False, comment="Human-readable name, e.g. 'caranddriver_reviews_daily'."),
    sa.Column('scraper_class', sa.String(length=200), nullable=False, comment='Fully-qualified Python class path for the scraper.'),
    sa.Column('target_url_pattern', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False, comment='1=high, 2=normal, 3=low.'),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD', name='task_status', create_constraint=True), nullable=False, comment='Lifecycle state of this task.'),
    sa.Column('max_retries', sa.SmallInteger(), nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('config_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Per-task overrides for scraper settings (headers, delays, etc.).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 3', name='chk_task_priority'),
    sa.CheckConstraint('retry_count <= max_retries', name='chk_task_retry_bound'),
    sa.PrimaryKeyConstraint('id'),
    comment='Master table of scraping directives - one row per site/task to be scraped.'
    )
    op.create_index('idx_tasks_created', 'scraping_tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_priority_status', 'scraping_tasks', ['priority', 'status'], unique=False)
    op.create_index('idx_tasks_scheduled', 'scraping_tasks', ['scheduled_at'], unique=False)
    op.create_index('idx_tasks_status', 'scraping_tasks', ['status'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_label', sa.String(length=200), nullable=False),
    sa.Column('top_words', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('domain', sa.Enum('AUTOMOTIVE', 'INSURANCE', 'GENERAL', name='entity_domain', create_constraint=True), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Each row is a BERTopic-discovered topic cluster, versioned per model run.'
    )
    op.create_index('idx_topics_domain', 'topics', ['domain'], unique=False)
    op.create_index('idx_topics_model', 'topics', ['model_version'], unique=False)
    op.create_table('car_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('engine_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('year BETWEEN 1900 AND 2100', name='chk_model_year'),
    sa.ForeignKeyConstraint(['brand_id'], ['car_brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name', 'year', name='uq_model_brand_name_year'),
    comment='Specific model-year, e.g. Toyota Corolla 2023.'
    )
    op.create_index('idx_models_active', 'car_models', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_models_brand', 'car_models', ['brand_id'], unique=False)
    op.create_index('idx_models_engine', 'car_models', ['engine_type'], unique=False)
    op.create_index('idx_models_segment', 'car_models', ['segment'], unique=False)
    op.create_index('idx_models_year', 'car_models', ['year'], unique=False)
    op.create_table('data_quality_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_task_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_task_id'], ['scraping_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Append-only dead-letter queue - never delete rows; used for data quality audits.'
    )
    op.create_index('idx_dql_entity', 'data_quality_log', ['entity_type'], unique=False)
    op.create_index('idx_dql_task', 'data_quality_log', ['scrape_task_id'], unique=False)
    op.create_index('idx_dql_rejected', 'data_quality_log', ['rejected_at'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('coverage_type', sa.Enum('COMPREHENSIVE', 'THIRD_PARTY', 'THIRD_PARTY_FIRE_THEFT', 'LIABILITY', 'OTHER', name='coverage_type', create_constraint=True), nullable=True),
    sa.Column('price_range_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_range_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='chk_policy_currency_len'),
    sa.CheckConstraint('price_range_max IS NULL OR price_range_max >= price_range_min', name='chk_policy_price_range'),
    sa.CheckConstraint('price_range_min > 0', name='chk_policy_price_min'),
    sa.ForeignKeyConstraint(['company_id'], ['insurance_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='A specific product/tier offered by an insurance_company.'
    )
    op.create_index('idx_policies_active', 'insurance_policies', ['is_active'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_policies_company', 'insurance_policies', ['company_id'], unique=False)
    op.create_index('idx_policies_coverage', 'insurance_policies', ['coverage_type'], unique=False)
    op.create_index('idx_policies_source', 'insurance_policies', ['source_id'], unique=False)
    op.create_table('insurance_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_title', sa.Text(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(review_text) > 0', name='chk_ir_nonempty'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='chk_ir_confidence'),
    sa.CheckConstraint('rating BETWEEN 1.0 AND 5.0', name='chk_insurance_review_rating'),
    sa.ForeignKeyConstraint(['company_id'], ['insurance_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'scraped_at'),
    comment='Partitioned review archive; content_hash deduplicates re-scrapes.',
    postgresql_partition_by='RANGE (scraped_at)'
    )
    op.create_index('idx_ir_company', 'insurance_reviews', ['company_id'], unique=False)
    op.create_index('idx_ir_company_scraped', 'insurance_reviews', ['company_id', 'scraped_at'], unique=False)
    op.create_index('idx_ir_date', 'insurance_reviews', ['review_date'], unique=False)
    op.create_index('idx_ir_hash', 'insurance_reviews', ['content_hash'], unique=False)
    op.create_index('idx_ir_rating', 'insurance_reviews', ['rating'], unique=False)
    op.create_index('idx_ir_source', 'insurance_reviews', ['source_id'], unique=False)
    op.create_index('idx_ir_unprocessed', 'insurance_reviews', ['is_processed'], unique=False, postgresql_where=sa.text('is_processed = FALSE'))
    op.create_table('market_trend_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 deduplication hash.'),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='Phase 6: 0-1 source reliability score.'),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='chk_mta_confidence'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('source_url'),
    comment='News and trend article archive; content_hash deduplicates re-scrapes.'
    )
    op.create_index('idx_mta_hash', 'market_trend_articles', ['content_hash'], unique=False)
    op.create_index('idx_mta_pub_date', 'market_trend_articles', ['publication_date'], unique=False)
    op.create_index('idx_mta_scraped', 'market_trend_articles', ['scraped_at'], unique=False)
    op.create_index('idx_mta_source', 'market_trend_articles', ['source_id'], unique=False)
    op.create_index('idx_mta_unprocessed', 'market_trend_articles', ['is_processed'], unique=False, postgresql_where=sa.text('is_processed = FALSE'))
    op.create_table('raw_api_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_task_id', sa.UUID(), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('http_status_code BETWEEN 100 AND 599', name='chk_api_status'),
    sa.CheckConstraint('response_size_bytes >= 0', name='chk_api_size'),
    sa.ForeignKeyConstraint(['scrape_task_id'], ['scraping_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Raw API response archive - never overwrite, always insert.'
    )
    op.create_index('idx_raw_api_task', 'raw_api_responses', ['scrape_task_id'], unique=False)
    op.create_index('idx_raw_api_scraped', 'raw_api_responses', ['scraped_at'], unique=False)
    op.create_index('idx_raw_api_unparsed', 'raw_api_responses', ['is_parsed'], unique=False, postgresql_where=sa.text('is_parsed = FALSE'))
    op.create_table('raw_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_task_id', sa.UUID(), nullable=True, comment='Phase 6: lineage - links raw HTML back to the originating task.'),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.String(length=200), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 of raw_html for change-detection deduplication.'),
    sa.Column('scraper_version', sa.String(length=50), nullable=True, comment='Version tag of the scraper that produced this row.'),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('http_status_code BETWEEN 100 AND 599', name='chk_raw_page_status'),
    sa.ForeignKeyConstraint(['scrape_task_id'], ['scraping_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable raw HTML archive - rows are never updated after insert.'
    )
    op.create_index('idx_raw_pages_domain', 'raw_pages', ['source_domain'], unique=False)
    op.create_index('idx_raw_pages_hash', 'raw_pages', ['content_hash'], unique=False)
    op.create_index('idx_raw_pages_task', 'raw_pages', ['scrape_task_id'], unique=False)
    op.create_index('idx_raw_pages_scraped', 'raw_pages', ['scraped_at'], unique=False)
    op.create_index('idx_raw_pages_unparsed', 'raw_pages', ['is_parsed'], unique=False, postgresql_where=sa.text('is_parsed = FALSE'))
    op.create_table('raw_scrape_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_task_id', sa.UUID(), nullable=True),
    sa.Column('scraper_name', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'SKIPPED', 'RATE_LIMITED', 'TIMEOUT', name='scrape_log_status', create_constraint=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='chk_log_attempt'),
    sa.CheckConstraint('bytes_downloaded >= 0', name='chk_log_bytes'),
    sa.CheckConstraint('duration_ms >= 0', name='chk_log_duration'),
    sa.ForeignKeyConstraint(['scrape_task_id'], ['scraping_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Detailed per-request log for rate-limit analysis and debugging.'
    )
    op.create_index('idx_scrape_logs_task', 'raw_scrape_logs', ['scrape_task_id'], unique=False)
    op.create_index('idx_scrape_logs_logged', 'raw_scrape_logs', ['logged_at'], unique=False)
    op.create_index('idx_scrape_logs_scraper_status', 'raw_scrape_logs', ['scraper_name', 'status'], unique=False)
    op.create_index('idx_scrape_logs_status', 'raw_scrape_logs', ['status'], unique=False)
    op.create_table('review_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.Enum('CAR', 'INSURANCE', 'ARTICLE', name='review_type', create_constraint=True), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name='chk_kw_score'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id', 'review_id', 'review_type', name='uq_review_keyword'),
    comment='Join table connecting keywords to any review type; score = TF-IDF or similar.'
    )
    op.create_index('idx_rk_entity', 'review_keywords', ['review_type', 'review_id'], unique=False)
    op.create_index('idx_rk_keyword', 'review_keywords', ['keyword_id'], unique=False)
    op.create_index('idx_rk_score', 'review_keywords', ['score'], unique=False)
    op.create_table('scraping_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', 'TIMEOUT', name='run_status', create_constraint=True), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exit_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bytes_downloaded >= 0', name='chk_run_bytes'),
    sa.CheckConstraint('pages_fetched >= 0', name='chk_run_pages'),
    sa.CheckConstraint('records_rejected <= records_extracted', name='chk_run_rejected_bound'),
    sa.ForeignKeyConstraint(['task_id'], ['scraping_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Each row is one execution attempt of a scraping_task, including automated retries.'
    )
    op.create_index('idx_runs_task', 'scraping_runs', ['task_id'], unique=False)
    op.create_index('idx_runs_task_status', 'scraping_runs', ['task_id', 'status'], unique=False)
    op.create_index('idx_runs_started', 'scraping_runs', ['started_at'], unique=False)
    op.create_index('idx_runs_status', 'scraping_runs', ['status'], unique=False)
    op.create_table('article_nlp_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment_label', create_constraint=True), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sentiment_score BETWEEN -1.0 AND 1.0', name='chk_anr_sentiment_score'),
    sa.ForeignKeyConstraint(['article_id'], ['market_trend_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'model_version', name='uq_anr_article_model'),
    comment='One NLP result per (article, model_version).'
    )
    op.create_index('idx_anr_article', 'article_nlp_results', ['article_id'], unique=False)
    op.create_index('idx_anr_sentiment', 'article_nlp_results', ['sentiment_label'], unique=False)
    op.create_index('idx_anr_topic', 'article_nlp_results', ['topic_id'], unique=False)
    op.create_index('idx_anr_topic_processed', 'article_nlp_results', ['topic_id', 'processed_at'], unique=False)
    op.create_table('car_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('dealer_name', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'USED', 'CERTIFIED', name='listing_condition', create_constraint=True), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('listed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='ISO 4217 currency code (always 3 chars).'),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='chk_listing_currency_len'),
    sa.CheckConstraint('listed_price > 0', name='chk_listing_price'),
    sa.CheckConstraint('mileage_km >= 0', name='chk_mileage'),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_url'),
    comment='Granular marketplace listings - complement aggregate car_price_history.'
    )
    op.create_index('idx_listings_condition', 'car_listings', ['condition'], unique=False)
    op.create_index('idx_listings_model', 'car_listings', ['model_id'], unique=False)
    op.create_index('idx_listings_model_scraped', 'car_listings', ['model_id', 'scraped_at'], unique=False)
    op.create_index('idx_listings_price', 'car_listings', ['listed_price'], unique=False)
    op.create_index('idx_listings_scraped', 'car_listings', ['scraped_at'], unique=False)
    op.create_index('idx_listings_source', 'car_listings', ['source_id'], unique=False)
    op.create_table('car_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('listed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_type', sa.Enum('MSRP', 'DEALER_LISTED', 'AUCTION', 'ESTIMATED', name='price_type', create_constraint=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='Phase 6: 0-1 confidence of price accuracy from source reliability.'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='chk_cph_currency_len'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='chk_cph_confidence'),
    sa.CheckConstraint('listed_price > 0', name='chk_car_price_positive'),
    sa.CheckConstraint('version >= 1', name='chk_cph_version'),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'scraped_at'),
    comment='One row per price observation; never UPDATE - only INSERT + mark old row is_latest=FALSE.',
    postgresql_partition_by='RANGE (scraped_at)'
    )
    op.create_index('idx_cph_latest', 'car_price_history', ['model_id', 'is_latest'], unique=False, postgresql_where=sa.text('is_latest = TRUE'))
    op.create_index('idx_cph_model_scraped', 'car_price_history', ['model_id', 'scraped_at'], unique=False)
    op.create_index('idx_cph_source', 'car_price_history', ['source_id'], unique=False)
    op.create_table('car_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_title', sa.Text(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='Phase 6: 0-1 score derived from source reliability.'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 deduplication hash - duplicate rows are rejected on insert.'),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(review_text) > 0', name='chk_car_review_nonempty'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='chk_car_review_confidence'),
    sa.CheckConstraint('rating BETWEEN 1.0 AND 5.0', name='chk_car_review_rating'),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'scraped_at'),
    comment='Partitioned review archive; content_hash deduplicates re-scrapes.',
    postgresql_partition_by='RANGE (scraped_at)'
    )
    op.create_index('idx_cr_date', 'car_reviews', ['review_date'], unique=False)
    op.create_index('idx_cr_hash', 'car_reviews', ['content_hash'], unique=False)
    op.create_index('idx_cr_model', 'car_reviews', ['model_id'], unique=False)
    op.create_index('idx_cr_model_scraped', 'car_reviews', ['model_id', 'scraped_at'], unique=False)
    op.create_index('idx_cr_rating', 'car_reviews', ['rating'], unique=False)
    op.create_index('idx_cr_source', 'car_reviews', ['source_id'], unique=False)
    op.create_index('idx_cr_unprocessed', 'car_reviews', ['is_processed'], unique=False, postgresql_where=sa.text('is_processed = FALSE'))
    op.create_table('competitor_pricings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coverage_type', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='chk_cp_currency_len'),
    sa.CheckConstraint('price > 0', name='chk_competitor_price'),
    sa.ForeignKeyConstraint(['company_id'], ['insurance_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Market-level price snapshots across competitors - used for pricing dashboards.'
    )
    op.create_index('idx_cp_company_date', 'competitor_pricings', ['company_id', 'snapshot_date'], unique=False)
    op.create_index('idx_cp_coverage', 'competitor_pricings', ['coverage_type'], unique=False)
    op.create_index('idx_cp_policy', 'competitor_pricings', ['policy_id'], unique=False)
    op.create_index('idx_cp_snapshot', 'competitor_pricings', ['snapshot_date'], unique=False)
    op.create_index('idx_cp_source', 'competitor_pricings', ['source_id'], unique=False)
    op.create_table('insurance_quote_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coverage_level', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='Phase 6: 0-1 confidence from source reliability.'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='chk_iqh_currency_len'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='chk_iqh_confidence'),
    sa.CheckConstraint('quoted_price > 0', name='chk_quote_price'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='chk_iqh_valid_dates'),
    sa.CheckConstraint('version >= 1', name='chk_iqh_version'),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'scraped_at'),
    comment='Append-only quote history - use is_latest=TRUE for current prices.',
    postgresql_partition_by='RANGE (scraped_at)'
    )
    op.create_index('idx_iqh_latest', 'insurance_quote_history', ['policy_id', 'is_latest'], unique=False, postgresql_where=sa.text('is_latest = TRUE'))
    op.create_index('idx_iqh_policy_scraped', 'insurance_quote_history', ['policy_id', 'scraped_at'], unique=False)
    op.create_index('idx_iqh_source', 'insurance_quote_history', ['source_id'], unique=False)
    op.create_table('insurance_review_nlp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment_label', create_constraint=True), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('complaint_type_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False, comment='Phase 6: NLP model version tag.'),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sentiment_score BETWEEN -1.0 AND 1.0', name='chk_ins_nlp_score'),
    sa.ForeignKeyConstraint(['complaint_type_id'], ['complaint_types.id'], ondelete='SET NULL'),
    # FK to insurance_reviews omitted: PG can't FK-reference a partitioned table's non-full-PK column
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'model_version', name='uq_ins_nlp_review_model'),
    comment='One NLP result row per (review, model_version); supports model comparison.'
    )
    op.create_index('idx_irnlp_complaint', 'insurance_review_nlp', ['complaint_type_id'], unique=False)
    op.create_index('idx_irnlp_review', 'insurance_review_nlp', ['review_id'], unique=False)
    op.create_index('idx_irnlp_sentiment', 'insurance_review_nlp', ['sentiment_label'], unique=False)
    op.create_index('idx_irnlp_topic', 'insurance_review_nlp', ['topic_id'], unique=False)
    op.create_index('idx_irnlp_topic_processed', 'insurance_review_nlp', ['topic_id', 'processed_at'], unique=False)
    op.create_table('scraper_health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scraper_name', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rate_limit_hits', sa.Integer(), nullable=False),
    sa.Column('robots_blocked_count', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_response_time_ms >= 0', name='chk_avg_response_time'),
    sa.CheckConstraint('error_rate BETWEEN 0 AND 1', name='chk_error_rate'),
    sa.CheckConstraint('success_rate + error_rate <= 1.0001', name='chk_rate_sum'),
    sa.CheckConstraint('success_rate BETWEEN 0 AND 1', name='chk_success_rate'),
    sa.ForeignKeyConstraint(['run_id'], ['scraping_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='One row per (run, scraper_name) - used for SLA monitoring dashboards.'
    )
    op.create_index('idx_health_run', 'scraper_health_metrics', ['run_id'], unique=False)
    op.create_index('idx_health_scraper_time', 'scraper_health_metrics', ['scraper_name', 'measured_at'], unique=False)
    op.create_table('scraping_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scraping_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scraping_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Append-only error log; never update rows.'
    )
    op.create_index('idx_errors_task', 'scraping_errors', ['task_id'], unique=False)
    op.create_index('idx_errors_occurred', 'scraping_errors', ['occurred_at'], unique=False)
    op.create_index('idx_errors_run', 'scraping_errors', ['run_id'], unique=False)
    op.create_index('idx_errors_type', 'scraping_errors', ['error_type'], unique=False)
    op.create_table('car_review_nlp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment_label', create_constraint=True), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('complaint_type_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False, comment="Phase 6: NLP model version tag, e.g. 'distilbert-v1.2'."),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sentiment_score BETWEEN -1.0 AND 1.0', name='chk_car_nlp_score'),
    sa.ForeignKeyConstraint(['complaint_type_id'], ['complaint_types.id'], ondelete='SET NULL'),
    # FK to car_reviews omitted: PG can't FK-reference a partitioned table's non-full-PK column
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'model_version', name='uq_car_nlp_review_model'),
    comment='One NLP result row per (review, model_version); supports model comparison.'
    )
    op.create_index('idx_crnlp_complaint', 'car_review_nlp', ['complaint_type_id'], unique=False)
    op.create_index('idx_crnlp_review', 'car_review_nlp', ['review_id'], unique=False)
    op.create_index('idx_crnlp_sentiment', 'car_review_nlp', ['sentiment_label'], unique=False)
    op.create_index('idx_crnlp_topic', 'car_review_nlp', ['topic_id'], unique=False)
    op.create_index('idx_crnlp_topic_processed', 'car_review_nlp', ['topic_id', 'processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_crnlp_topic_processed', table_name='car_review_nlp')
    op.drop_index('idx_crnlp_topic', table_name='car_review_nlp')
    op.drop_index('idx_crnlp_sentiment', table_name='car_review_nlp')
    op.drop_index('idx_crnlp_review', table_name='car_review_nlp')
    op.drop_index('idx_crnlp_complaint', table_name='car_review_nlp')
    op.drop_table('car_review_nlp')
    op.drop_index('idx_errors_type', table_name='scraping_errors')
    op.drop_index('idx_errors_run', table_name='scraping_errors')
    op.drop_index('idx_errors_occurred', table_name='scraping_errors')
    op.drop_index('idx_errors_task', table_name='scraping_errors')
    op.drop_table('scraping_errors')
    op.drop_index('idx_health_scraper_time', table_name='scraper_health_metrics')
    op.drop_index('idx_health_run', table_name='scraper_health_metrics')
    op.drop_table('scraper_health_metrics')
    op.drop_index('idx_irnlp_topic_processed', table_name='insurance_review_nlp')
    op.drop_index('idx_irnlp_topic', table_name='insurance_review_nlp')
    op.drop_index('idx_irnlp_sentiment', table_name='insurance_review_nlp')
    op.drop_index('idx_irnlp_review', table_name='insurance_review_nlp')
    op.drop_index('idx_irnlp_complaint', table_name='insurance_review_nlp')
    op.drop_table('insurance_review_nlp')
    op.drop_index('idx_iqh_source', table_name='insurance_quote_history')
    op.drop_index('idx_iqh_policy_scraped', table_name='insurance_quote_history')
    op.drop_index('idx_iqh_latest', table_name='insurance_quote_history', postgresql_where=sa.text('is_latest = TRUE'))
    op.drop_table('insurance_quote_history')
    op.drop_index('idx_cp_source', table_name='competitor_pricings')
    op.drop_index('idx_cp_snapshot', table_name='competitor_pricings')
    op.drop_index('idx_cp_policy', table_name='competitor_pricings')
    op.drop_index('idx_cp_coverage', table_name='competitor_pricings')
    op.drop_index('idx_cp_company_date', table_name='competitor_pricings')
    op.drop_table('competitor_pricings')
    op.drop_index('idx_cr_unprocessed', table_name='car_reviews', postgresql_where=sa.text('is_processed = FALSE'))
    op.drop_index('idx_cr_source', table_name='car_reviews')
    op.drop_index('idx_cr_rating', table_name='car_reviews')
    op.drop_index('idx_cr_model_scraped', table_name='car_reviews')
    op.drop_index('idx_cr_model', table_name='car_reviews')
    op.drop_index('idx_cr_hash', table_name='car_reviews')
    op.drop_index('idx_cr_date', table_name='car_reviews')
    op.drop_table('car_reviews')
    op.drop_index('idx_cph_source', table_name='car_price_history')
    op.drop_index('idx_cph_model_scraped', table_name='car_price_history')
    op.drop_index('idx_cph_latest', table_name='car_price_history', postgresql_where=sa.text('is_latest = TRUE'))
    op.drop_table('car_price_history')
    op.drop_index('idx_listings_source', table_name='car_listings')
    op.drop_index('idx_listings_scraped', table_name='car_listings')
    op.drop_index('idx_listings_price', table_name='car_listings')
    op.drop_index('idx_listings_model_scraped', table_name='car_listings')
    op.drop_index('idx_listings_model', table_name='car_listings')
    op.drop_index('idx_listings_condition', table_name='car_listings')
    op.drop_table('car_listings')
    op.drop_index('idx_anr_topic_processed', table_name='article_nlp_results')
    op.drop_index('idx_anr_topic', table_name='article_nlp_results')
    op.drop_index('idx_anr_sentiment', table_name='article_nlp_results')
    op.drop_index('idx_anr_article', table_name='article_nlp_results')
    op.drop_table('article_nlp_results')
    op.drop_index('idx_runs_status', table_name='scraping_runs')
    op.drop_index('idx_runs_started', table_name='scraping_runs')
    op.drop_index('idx_runs_task_status', table_name='scraping_runs')
    op.drop_index('idx_runs_task', table_name='scraping_runs')
    op.drop_table('scraping_runs')
    op.drop_index('idx_rk_score', table_name='review_keywords')
    op.drop_index('idx_rk_keyword', table_name='review_keywords')
    op.drop_index('idx_rk_entity', table_name='review_keywords')
    op.drop_table('review_keywords')
    op.drop_index('idx_scrape_logs_status', table_name='raw_scrape_logs')
    op.drop_index('idx_scrape_logs_scraper_status', table_name='raw_scrape_logs')
    op.drop_index('idx_scrape_logs_logged', table_name='raw_scrape_logs')
    op.drop_index('idx_scrape_logs_task', table_name='raw_scrape_logs')
    op.drop_table('raw_scrape_logs')
    op.drop_index('idx_raw_pages_unparsed', table_name='raw_pages', postgresql_where=sa.text('is_parsed = FALSE'))
    op.drop_index('idx_raw_pages_scraped', table_name='raw_pages')
    op.drop_index('idx_raw_pages_task', table_name='raw_pages')
    op.drop_index('idx_raw_pages_hash', table_name='raw_pages')
    op.drop_index('idx_raw_pages_domain', table_name='raw_pages')
    op.drop_table('raw_pages')
    op.drop_index('idx_raw_api_unparsed', table_name='raw_api_responses', postgresql_where=sa.text('is_parsed = FALSE'))
    op.drop_index('idx_raw_api_scraped', table_name='raw_api_responses')
    op.drop_index('idx_raw_api_task', table_name='raw_api_responses')
    op.drop_table('raw_api_responses')
    op.drop_index('idx_mta_unprocessed', table_name='market_trend_articles', postgresql_where=sa.text('is_processed = FALSE'))
    op.drop_index('idx_mta_source', table_name='market_trend_articles')
    op.drop_index('idx_mta_scraped', table_name='market_trend_articles')
    op.drop_index('idx_mta_pub_date', table_name='market_trend_articles')
    op.drop_index('idx_mta_hash', table_name='market_trend_articles')
    op.drop_table('market_trend_articles')
    op.drop_index('idx_ir_unprocessed', table_name='insurance_reviews', postgresql_where=sa.text('is_processed = FALSE'))
    op.drop_index('idx_ir_source', table_name='insurance_reviews')
    op.drop_index('idx_ir_rating', table_name='insurance_reviews')
    op.drop_index('idx_ir_hash', table_name='insurance_reviews')
    op.drop_index('idx_ir_date', table_name='insurance_reviews')
    op.drop_index('idx_ir_company_scraped', table_name='insurance_reviews')
    op.drop_index('idx_ir_company', table_name='insurance_reviews')
    op.drop_table('insurance_reviews')
    op.drop_index('idx_policies_source', table_name='insurance_policies')
    op.drop_index('idx_policies_coverage', table_name='insurance_policies')
    op.drop_index('idx_policies_company', table_name='insurance_policies')
    op.drop_index('idx_policies_active', table_name='insurance_policies', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('insurance_policies')
    op.drop_index('idx_dql_rejected', table_name='data_quality_log')
    op.drop_index('idx_dql_task', table_name='data_quality_log')
    op.drop_index('idx_dql_entity', table_name='data_quality_log')
    op.drop_table('data_quality_log')
    op.drop_index('idx_models_year', table_name='car_models')
    op.drop_index('idx_models_segment', table_name='car_models')
    op.drop_index('idx_models_engine', table_name='car_models')
    op.drop_index('idx_models_brand', table_name='car_models')
    op.drop_index('idx_models_active', table_name='car_models', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('car_models')
    op.drop_index('idx_topics_model', table_name='topics')
    op.drop_index('idx_topics_domain', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_tasks_status', table_name='scraping_tasks')
    op.drop_index('idx_tasks_scheduled', table_name='scraping_tasks')
    op.drop_index('idx_tasks_priority_status', table_name='scraping_tasks')
    op.drop_index('idx_tasks_created', table_name='scraping_tasks')
    op.drop_table('scraping_tasks')
    op.drop_index('idx_sources_type', table_name='review_sources')
    op.drop_index('idx_sources_active', table_name='review_sources', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('review_sources')
    op.drop_index('idx_pipeline_task_start', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_task', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_status', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_start', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('idx_kpi_name_computed', table_name='kpi_metrics')
    op.drop_index('idx_kpi_granularity', table_name='kpi_metrics')
    op.drop_index('idx_kpi_entity', table_name='kpi_metrics')
    op.drop_table('kpi_metrics')
    op.drop_index('idx_keywords_domain', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('idx_insurers_name', table_name='insurance_companies')
    op.drop_index('idx_insurers_country', table_name='insurance_companies')
    op.drop_index('idx_insurers_active', table_name='insurance_companies', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('insurance_companies')
    op.drop_index('idx_complaint_domain', table_name='complaint_types')
    op.drop_table('complaint_types')
    op.drop_index('idx_brands_name', table_name='car_brands')
    op.drop_index('idx_brands_active', table_name='car_brands', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('car_brands')
    # ### end Alembic commands ###
