"""add_ml_model_metrics

Revision ID: 73c028bd9bfa
Revises: 4eb47a85ad62
Create Date: 2026-04-03 12:13:31.545805

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73c028bd9bfa'
down_revision: Union[str, None] = '4eb47a85ad62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('silhouette_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('davies_bouldin_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('inertia', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('k_value', sa.Integer(), nullable=False),
    sa.Column('n_companies', sa.Integer(), nullable=False),
    sa.Column('cluster_stability_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Bootstrap stability percentages per company { company_id: stability_pct }.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores analytical metrics like Silhouette score, Davies-Bouldin, and bootstrap stability per ML model run.'
    )
    op.create_index('idx_mlmm_model', 'ml_model_metrics', ['model_name'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mlmm_model', table_name='ml_model_metrics')
    op.drop_table('ml_model_metrics')
    # ### end Alembic commands ###ands ###
