"""
scripts/build_training_set.py
------------------------------
Professional data preparation pipeline for sentiment fine-tuning.

Design principles applied:
  1. Stratified split — each class × corpus stratum (e.g. positive_car,
     negative_insurance) is split independently so all combinations are
     proportionally represented in every partition.
  2. Clean test set — held-out 15% split is never used during training or
     hyper-parameter selection.  Only used for final evaluation.
  3. Natural distribution on val/test — no balancing.  The evaluation
     reflects real-world class frequencies.
  4. Balanced training only — majority classes are undersampled in the
     training partition so the model sees equal class exposure.
  5. Source discipline — Groq pseudo-labels are added to training only
     (neutral class supplement).  They are excluded from val/test which
     use only rating-anchored ground truth.
  6. Ambiguous ratings excluded — reviews rated 2.0-2.5 or 3.5-4.5 cannot
     be reliably labeled positive/neutral/negative and are dropped.
  7. Deduplication — exact-text duplicates removed before splitting.
  8. Distribution report — printed and saved to JSON for the academic paper.

Label mapping:
  rating >= 4.5          → positive
  2.5 <= rating <= 3.5   → neutral
  rating <= 2.0          → negative

Output files:
  data/train_set.jsonl   — balanced training set
  data/val_set.jsonl     — natural distribution, rating-anchored (replaces
                           the one generated by finetune_sentiment.py)
  data/test_set.jsonl    — held-out, natural distribution, NEVER used in
                           training
  data/split_report.json — full distribution statistics for the paper

Usage:
    python -m scripts.build_training_set
    python -m scripts.build_training_set --target 200
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

GROQ_LABELS_PATH = _ROOT / "data" / "llm_labels.jsonl"
TRAIN_OUT  = _ROOT / "data" / "train_set.jsonl"
VAL_OUT    = _ROOT / "data" / "val_set.jsonl"
TEST_OUT   = _ROOT / "data" / "test_set.jsonl"
REPORT_OUT = _ROOT / "data" / "split_report.json"

VAL_RATIO  = 0.15
TEST_RATIO = 0.15
MIN_TEXT_LEN  = 20      # characters
MAX_TEXT_CHARS = 500    # truncate to match training
DEFAULT_TARGET = 200    # balanced samples per class in training
SEED = 42

LABEL2ID = {"negative": 0, "neutral": 1, "positive": 2}


# ---------------------------------------------------------------------------
# Step 1 — Collect rating-anchored samples from DB
# ---------------------------------------------------------------------------

def collect_rating_samples() -> list[dict]:
    from database.connection import get_db_session
    from database.models import CarReview, InsuranceReview

    samples: list[dict] = []
    seen_texts: set[str] = set()

    def _classify(rating: float) -> str | None:
        if rating >= 4.5:
            return "positive"
        if 2.5 <= rating <= 3.5:
            return "neutral"
        if rating <= 2.0:
            return "negative"
        return None  # ambiguous — excluded

    with get_db_session() as session:
        for Model, corpus_name in [
            (CarReview,       "car_review"),
            (InsuranceReview, "insurance_review"),
        ]:
            rows = (
                session.query(Model)
                .filter(Model.data_origin == "scraped")
                .filter(Model.review_text.isnot(None))
                .filter(Model.rating.isnot(None))
                .all()
            )
            for row in rows:
                rating = float(row.rating)
                sentiment = _classify(rating)
                if sentiment is None:
                    continue
                title = getattr(row, "review_title", None) or ""
                text  = f"{title} {row.review_text}".strip()[:MAX_TEXT_CHARS]
                if len(text) < MIN_TEXT_LEN:
                    continue
                # Exact-text dedup
                key = text[:100].lower()
                if key in seen_texts:
                    continue
                seen_texts.add(key)
                samples.append({
                    "id":        str(row.id),
                    "text":      text,
                    "sentiment": sentiment,
                    "label":     LABEL2ID[sentiment],
                    "corpus":    corpus_name,
                    "source":    "rating",
                    "confidence": 1.0,
                    "rating":    rating,
                })
    return samples


# ---------------------------------------------------------------------------
# Step 2 — Collect Groq neutral labels (train-only supplement)
# ---------------------------------------------------------------------------

def collect_groq_neutrals(existing_ids: set[str]) -> list[dict]:
    if not GROQ_LABELS_PATH.exists():
        return []
    seen_texts: set[str] = set()
    rows = []
    with GROQ_LABELS_PATH.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            if obj.get("sentiment") != "neutral":
                continue
            if float(obj.get("confidence", 0)) < 0.70:
                continue
            if obj["id"] in existing_ids:
                continue
            text = obj.get("text", "").strip()
            if len(text) < MIN_TEXT_LEN:
                continue
            key = text[:100].lower()
            if key in seen_texts:
                continue
            seen_texts.add(key)
            rows.append({
                "id":        obj["id"],
                "text":      text[:MAX_TEXT_CHARS],
                "sentiment": "neutral",
                "label":     LABEL2ID["neutral"],
                "corpus":    obj.get("corpus", "unknown"),
                "source":    "groq",
                "confidence": float(obj["confidence"]),
            })
    return rows


# ---------------------------------------------------------------------------
# Step 3 — Stratified 70/15/15 split
#
# Strata = sentiment × corpus (e.g. positive_car, negative_insurance …)
# Each stratum is split independently so all combinations are proportionally
# represented in every partition.
# ---------------------------------------------------------------------------

def stratified_split(
    samples: list[dict],
    val_ratio: float = VAL_RATIO,
    test_ratio: float = TEST_RATIO,
    seed: int = SEED,
) -> tuple[list[dict], list[dict], list[dict]]:

    rng = np.random.default_rng(seed)

    # Group by stratum
    strata: dict[str, list[dict]] = defaultdict(list)
    for s in samples:
        key = f"{s['sentiment']}_{s['corpus']}"
        strata[key].append(s)

    train_all, val_all, test_all = [], [], []

    for stratum_key, group in strata.items():
        n = len(group)
        idx = rng.permutation(n)
        n_test = max(1, round(n * test_ratio))
        n_val  = max(1, round(n * val_ratio))
        n_train = n - n_test - n_val

        # Ensure at least 1 sample per partition even for tiny strata
        if n_train < 1:
            n_train = 1
            n_val   = max(0, n - n_train - n_test)

        test_idx  = idx[:n_test]
        val_idx   = idx[n_test:n_test + n_val]
        train_idx = idx[n_test + n_val:]

        test_all  += [group[i] for i in test_idx]
        val_all   += [group[i] for i in val_idx]
        train_all += [group[i] for i in train_idx]

    return train_all, val_all, test_all


# ---------------------------------------------------------------------------
# Step 4 — Balance training set
#
# Undersample majority classes to `target_per_class`.  The neutral class is
# often smaller — if it has fewer than target, all neutral samples are kept
# and target is NOT lowered for other classes (weighted loss compensates).
# ---------------------------------------------------------------------------

def balance_training(
    train_raw: list[dict],
    groq_neutrals: list[dict],
    target_per_class: int,
    seed: int = SEED,
) -> list[dict]:

    rng = np.random.default_rng(seed)

    # Add Groq neutrals (train-only supplement)
    combined = train_raw + groq_neutrals

    by_class: dict[str, list[dict]] = defaultdict(list)
    for s in combined:
        by_class[s["sentiment"]].append(s)

    balanced: list[dict] = []
    for sentiment, pool in by_class.items():
        n = min(target_per_class, len(pool))
        idx = rng.choice(len(pool), size=n, replace=False)
        balanced += [pool[i] for i in idx]

    rng.shuffle(balanced)
    return balanced


# ---------------------------------------------------------------------------
# Step 5 — Distribution statistics
# ---------------------------------------------------------------------------

def _dist_stats(samples: list[dict], label: str) -> dict:
    total = len(samples)
    by_sent  = Counter(s["sentiment"] for s in samples)
    by_corp  = Counter(s["corpus"]    for s in samples)
    by_src   = Counter(s["source"]    for s in samples)
    return {
        "label":  label,
        "total":  total,
        "by_sentiment": {
            k: {"count": v, "pct": round(100 * v / total, 1)}
            for k, v in sorted(by_sent.items())
        },
        "by_corpus": {
            k: {"count": v, "pct": round(100 * v / total, 1)}
            for k, v in sorted(by_corp.items())
        },
        "by_source": dict(by_src),
    }


def print_distribution(stats: dict) -> None:
    label = stats["label"]
    total = stats["total"]
    print(f"\n  [{label}]  n={total}")
    print(f"  {'Sentiment':<12}  {'Count':>6}  {'%':>6}   {'Corpus breakdown'}")
    print(f"  {'-'*60}")
    for sent, info in stats["by_sentiment"].items():
        print(f"  {sent:<12}  {info['count']:>6}  {info['pct']:>5.1f}%")
    print(f"  Corpus  : { {k: v['count'] for k, v in stats['by_corpus'].items()} }")
    print(f"  Source  : { stats['by_source'] }")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build(target_per_class: int) -> None:
    print(f"\n{'='*62}")
    print(f"  Professional Sentiment Data Pipeline")
    print(f"  Target per class (train) : {target_per_class}")
    print(f"  Split                    : 70% train / 15% val / 15% test")
    print(f"  Stratification           : class × corpus")
    print(f"  Neutral band             : 2.5 <= rating <= 3.5")
    print(f"{'='*62}\n")

    # ----- Step 1: collect rating-anchored data -----
    print("STEP 1  Collecting rating-anchored samples from database …")
    rating_samples = collect_rating_samples()
    rating_ids = {s["id"] for s in rating_samples}
    print(f"  Collected  : {len(rating_samples)} samples (after dedup + quality filter)")
    c = Counter(s["sentiment"] for s in rating_samples)
    for sent in ("positive", "neutral", "negative"):
        sub = [s for s in rating_samples if s["sentiment"] == sent]
        cc  = Counter(s["corpus"] for s in sub)
        print(f"  {sent:<10}: {c[sent]:5d}   "
              f"(car={cc.get('car_review',0)}, insurance={cc.get('insurance_review',0)})")

    # ----- Step 2: collect Groq neutral supplement -----
    print("\nSTEP 2  Collecting Groq neutral labels (train-only supplement) …")
    groq_neutrals = collect_groq_neutrals(rating_ids)
    print(f"  Groq neutrals: {len(groq_neutrals)}")

    # ----- Step 3: stratified 70/15/15 split -----
    print("\nSTEP 3  Stratified 70/15/15 split (class × corpus) …")
    train_raw, val_set, test_set = stratified_split(rating_samples)
    print(f"  train_raw : {len(train_raw)}")
    print(f"  val       : {len(val_set)}")
    print(f"  test      : {len(test_set)}")

    # Verify no overlap
    test_ids = {s["id"] for s in test_set}
    val_ids  = {s["id"] for s in val_set}
    tr_ids   = {s["id"] for s in train_raw}
    assert not (test_ids & val_ids),  "LEAK: test ∩ val"
    assert not (test_ids & tr_ids),   "LEAK: test ∩ train"
    assert not (val_ids  & tr_ids),   "LEAK: val ∩ train"
    print("  Leak check : PASSED — no overlap between partitions")

    # ----- Step 4: balance training set -----
    print(f"\nSTEP 4  Balancing training set (target={target_per_class} per class) …")
    train_set = balance_training(train_raw, groq_neutrals, target_per_class)
    c_train = Counter(s["sentiment"] for s in train_set)
    for sent in ("positive", "neutral", "negative"):
        print(f"  {sent:<10}: {c_train[sent]:4d}")

    # ----- Step 5: distribution report -----
    print("\nSTEP 5  Distribution report …")
    stats = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target_per_class": target_per_class,
        "train": _dist_stats(train_set, "TRAIN"),
        "val":   _dist_stats(val_set,   "VAL"),
        "test":  _dist_stats(test_set,  "TEST"),
    }
    for split in ("train", "val", "test"):
        print_distribution(stats[split])

    # Check val/test distributions match (KS-style proportion check)
    print("\n  Distribution consistency check (val vs test):")
    for sent in ("positive", "neutral", "negative"):
        pv = stats["val"]["by_sentiment"].get(sent, {}).get("pct", 0)
        pt = stats["test"]["by_sentiment"].get(sent, {}).get("pct", 0)
        diff = abs(pv - pt)
        flag = "OK" if diff < 5 else "WARN"
        print(f"    {sent:<10}: val={pv:.1f}%  test={pt:.1f}%  diff={diff:.1f}%  [{flag}]")

    # ----- Step 6: write output files -----
    print("\nSTEP 6  Writing output files …")
    for path, dataset in [
        (TRAIN_OUT, train_set),
        (VAL_OUT,   val_set),
        (TEST_OUT,  test_set),
    ]:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as fh:
            for row in dataset:
                fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        print(f"  {path.name:<22}: {len(dataset)} rows")

    REPORT_OUT.parent.mkdir(parents=True, exist_ok=True)
    with REPORT_OUT.open("w", encoding="utf-8") as fh:
        json.dump(stats, fh, indent=2, ensure_ascii=False)
    print(f"  {REPORT_OUT.name:<22}: distribution report")

    print(f"\n{'='*62}")
    print("  Data pipeline complete.")
    print(f"  train={len(train_set)}  val={len(val_set)}  test={len(test_set)}")
    print(f"{'='*62}\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build professional train/val/test splits for sentiment fine-tuning."
    )
    parser.add_argument(
        "--target", type=int, default=DEFAULT_TARGET,
        help=f"Max samples per class in training set (default: {DEFAULT_TARGET})."
    )
    args = parser.parse_args()
    build(args.target)


if __name__ == "__main__":
    main()
